phrases = {
  'pt-br': {
    'input_mainpath': "Diretório de análise (vazio para diretório local): ",
    'print_showpath': "Diretório assumido: {mainpath}",
    'print_containsfolder': "Contém pasta(s) aqui.",
    'input_indsaveinotherdirectory': "Você gostaria de salvar os novos arquivos dentro de um diretório separado (__newfiles__)? [y/N]: ",
    'input_endfilename': "Terminação do nome dos arquivos (vazio para \"_alt\" no caso de salvar no mesmo diretório): ",
    'input_newformat': "Qual o formato das novas imagens (vazio para jpg): ",
    'while_input_newformat': "O formato das novas imagens (vazio para jpg ou um desses: {permittedext}): ",
    'input_reducequalityfor': "Em percentual, qual nível de qualidade manter (vazio para não alterar a qualidade): ",
    'while_input_reducequalityfor': "Nível de qualidade a manter (vazio não alterar a qualidade ou algo entre 1 e 100): ",
    'input_maxwidth': "Em pixels, qual a largura máxima para as imagens (vazio para não alterar o tamanho): ",
    'print_advice_png_1': "Como você quer uma conversão para PNG, não será possível diminuir a qualidade da imagem.",
    'print_advice_png_2': "Para diminuir o tamanho dos arquivos, por favor, diminua suas dimensões.",
    'print_filesaved': "Arquivo \"{filetocreate}\" salvo ...",
    'print_languagenotset': "Linguagem não parametrizada. Será considerada a padrão (PT-BR).",
    'print_reducequalityforset': "Qualidade a ser mantida: {reducequalityfor}",
    'warn_cant_save_file': "Warning: Não foi possível salvar o arquivo \"{filetocreate}\".",
    'warn_cant_create_folder': "Warning: Não foi possível criar a pasta de receber os novos arquivos.",
    'warn_cant_create_subfolder': "Warning: Não foi possível criar a subpasta de receber os novos arquivos."
  },
  'es': {
    'input_mainpath': "Path de análise (vazio para path local): ",
    'print_showpath': "Caminho assumido: {mainpath}",
    'print_containsfolder': "Contém pasta(s) aqui.",
    'input_indsaveinotherdirectory': "Você gostaria de salvar os novos arquivos dentro de um diretório separado? [y/N]: ",
    'input_endfilename': "Terminação do nome dos arquivos (vazio para \"_alt\" no caso de salvar no mesmo diretório): ",
    'input_newformat': "Qual o formato das novas imagens (vazio para jpg): ",
    'while_input_newformat': "O formato das novas imagens (vazio para jpg ou ex.: {permittedext}): ",
    'input_reducequalityfor': "Em percentual, qual nível de qualidade manter (vazio para não alterar a qualidade): ",
    'while_input_reducequalityfor': "Nível de qualidade a manter (vazio não alterar a qualidade ou algo entre 0 e 100): ",
    'input_maxwidth': "Em pixels, qual a largura máxima para as imagens (vazio para não alterar o tamanho): ",
    'print_advice_png_1': "Como você quer uma conversão para PNG, não será possível diminuir a qualidade da imagem.",
    'print_advice_png_2': "Para diminuir o tamanho dos arquivos, por favor, diminua suas dimensões.",
    'print_filesaved': "File \"{filetocreate}\" saved ...",
    'print_languagenotset': "Linguagem não parametrizada. Será considerada a padrão (PT-BR).",
    'print_reducequalityforset': "Qualidade a ser mantida: {reducequalityfor}",
    'warn_cant_save_file': "Warning: Não foi possível salvar o arquivo \"{filetocreate}\".",
    'warn_cant_create_folder': "Warning: Não foi possível criar a pasta de receber os novos arquivos.",
    'warn_cant_create_subfolder': "Warning: Não foi possível criar a subpasta de receber os novos arquivos."
  },
  'pt': {
    'input_mainpath': "Path de análise (vazio para path local): ",
    'print_showpath': "Caminho assumido: {mainpath}",
    'print_containsfolder': "Contém pasta(s) aqui.",
    'input_indsaveinotherdirectory': "Você gostaria de salvar os novos arquivos dentro de um diretório separado? [y/N]: ",
    'input_endfilename': "Terminação do nome dos arquivos (vazio para \"_alt\" no caso de salvar no mesmo diretório): ",
    'input_newformat': "Qual o formato das novas imagens (vazio para jpg): ",
    'while_input_newformat': "O formato das novas imagens (vazio para jpg ou ex.: {permittedext}): ",
    'input_reducequalityfor': "Em percentual, qual nível de qualidade manter (vazio para não alterar a qualidade): ",
    'while_input_reducequalityfor': "Nível de qualidade a manter (vazio não alterar a qualidade ou algo entre 0 e 100): ",
    'input_maxwidth': "Em pixels, qual a largura máxima para as imagens (vazio para não alterar o tamanho): ",
    'print_advice_png_1': "Como você quer uma conversão para PNG, não será possível diminuir a qualidade da imagem.",
    'print_advice_png_2': "Para diminuir o tamanho dos arquivos, por favor, diminua suas dimensões.",
    'print_filesaved': "File \"{filetocreate}\" saved ...",
    'print_languagenotset': "Linguagem não parametrizada. Será considerada a padrão (PT-BR).",
    'print_reducequalityforset': "Qualidade a ser mantida: {reducequalityfor}",
    'warn_cant_save_file': "Warning: Não foi possível salvar o arquivo \"{filetocreate}\".",
    'warn_cant_create_folder': "Warning: Não foi possível criar a pasta de receber os novos arquivos.",
    'warn_cant_create_subfolder': "Warning: Não foi possível criar a subpasta de receber os novos arquivos."
  },
  'en': {
    'input_mainpath': "Path to analyse the files (empty for local path): ",
    'print_showpath': "Path set: {mainpath}",
    'print_containsfolder': "Contains folders here.",
    'input_indsaveinotherdirectory': "Você gostaria de salvar os novos arquivos dentro de um diretório separado? [y/N]: ",
    'input_endfilename': "Termination of file names (empty for \"_alt\" in case of saving at the same path): ",
    'input_newformat': "Qual o formato das novas imagens (vazio para jpg): ",
    'while_input_newformat': "O formato das novas imagens (vazio para jpg ou ex.: {permittedext}): ",
    'input_reducequalityfor': "In percentage, quality level (empty to keep current quality): ",
    'while_input_reducequalityfor': "Nível de qualidade a manter (vazio não alterar a qualidade ou algo entre 0 e 100): ",
    'input_maxwidth': "Em pixels, qual a largura máxima para as imagens (vazio para não alterar o tamanho): ",
    'print_advice_png_1': "Since you want a conversion to PNG, you won't be able to lower the image quality.",
    'print_advice_png_2': "To decrease the size of files, please decrease their dimensions.",
    'print_filesaved': "File \"{filetocreate}\" saved ...",
    'print_languagenotset': "Language not identified. Default is going to be set (EN).",
    'print_reducequalityforset': "Qualidade a ser mantida: {reducequalityfor}",
    'warn_cant_save_file': "Warning: Não foi possível salvar o arquivo \"{filetocreate}\".",
    'warn_cant_create_folder': "Warning: Não foi possível criar a pasta de receber os novos arquivos.",
    'warn_cant_create_subfolder': "Warning: Não foi possível criar a subpasta de receber os novos arquivos."
  }
}